version: '3.8'

services:
  email-agent:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./emails:/app/emails
      - ./output:/app/output
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
